### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by PanagiotisPtr** [mattysmith22/G51FAI#1]
Problem running the demo described in the README.md

Output:
>>> import problems.eightqueen as queen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panos/Documents/tmp/G51FAI/problems/eightqueen.py", line 1, in <module>
    import problems.abstract
  File "/home/panos/Documents/tmp/G51FAI/problems/abstract.py", line 46, in <module>
    class TreeNode(ABC):
  File "/home/panos/Documents/tmp/G51FAI/problems/abstract.py", line 54, in TreeNode
    @abstractmethodutility
NameError: name 'abstractmethodutility' is not defined

I think it might be an import issue.

**Comment by mattysmith22** [comment]
Or just that I am an absolute idiot and that `utility` should not be present in the name `abstractmethod`. Fixing.

**Comment by mattysmith22** [comment]
Thanks for the issue, should be fixed now.
